# Generated by Django 4.0.2 on 2024-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
