# Generated by Django 4.0.2 on 2024-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_business_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
